version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=data_load
    links:
      - db

  db:
    image: mysql:8.0
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_load
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
